### ISSUE TITLE
LinkStack Container exits immediatly on start after todays update (6/23/2023)

### ISSUE THREAD

**Issue by norton287** [LinkStackOrg/linkstack-docker#71] opened 2023-06-24 03:19 UTC
Logs show this:

exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

Not sure if maybe something was left out or a configuration problem.

**Comment by dw5** [comment] 2023-06-24 10:09
Tried installing on arm64, and yes IT'S THIS!

**Comment by JulianPrieber** [comment] 2023-06-24 12:16
Should be fixed now.

**Comment by norton287** [comment] 2023-06-24 12:39
Now getting these after starting the container @JulianPrieber

[Sat Jun 24 12:29:50.792641 2023] [ssl:info] [pid 31] [client 172.20.0.1:53734] AH01964: Connection to child 3 established (server www.example.com:443)
172.20.0.1 - - [24/Jun/2023:12:29:50 +0000] "GET / HTTP/1.1" 500 6609
[Sat Jun 24 12:29:51.185024 2023] [ssl:info] [pid 32] [client 172.20.0.1:53740] AH01964: Connection to child 4 established (server www.example.com:443)
172.20.0.1 - - [24/Jun/2023:12:29:51 +0000] "GET /favicon.ico HTTP/1.1" 404 6603
127.0.0.1 - - [24/Jun/2023:12:30:08 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:30:08 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:30:08.365111 2023] [ssl:info] [pid 28] [client 127.0.0.1:58168] AH01964: Connection to child 0 established (server www.example.com:443)
[Sat Jun 24 12:30:08.366950 2023] [ssl:info] [pid 28] [client 127.0.0.1:58168] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:30:08.366970 2023] [ssl:info] [pid 28] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:30:08.366976 2023] [ssl:info] [pid 28] [client 127.0.0.1:58168] AH01998: Connection closed to child 0 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:30:38 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:30:38 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:30:38.579778 2023] [ssl:info] [pid 30] [client 127.0.0.1:58284] AH01964: Connection to child 2 established (server www.example.com:443)
[Sat Jun 24 12:30:38.581775 2023] [ssl:info] [pid 30] [client 127.0.0.1:58284] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:30:38.581791 2023] [ssl:info] [pid 30] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:30:38.581796 2023] [ssl:info] [pid 30] [client 127.0.0.1:58284] AH01998: Connection closed to child 2 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:31:08 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:31:08 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:31:08.784088 2023] [ssl:info] [pid 32] [client 127.0.0.1:58488] AH01964: Connection to child 4 established (server www.example.com:443)
[Sat Jun 24 12:31:08.786099 2023] [ssl:info] [pid 32] [client 127.0.0.1:58488] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:31:08.786115 2023] [ssl:info] [pid 32] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:31:08.786120 2023] [ssl:info] [pid 32] [client 127.0.0.1:58488] AH01998: Connection closed to child 4 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:31:38 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:31:38 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:31:38.982908 2023] [ssl:info] [pid 28] [client 127.0.0.1:58638] AH01964: Connection to child 0 established (server www.example.com:443)
[Sat Jun 24 12:31:38.984737 2023] [ssl:info] [pid 28] [client 127.0.0.1:58638] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:31:38.984755 2023] [ssl:info] [pid 28] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:31:38.984761 2023] [ssl:info] [pid 28] [client 127.0.0.1:58638] AH01998: Connection closed to child 0 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:32:09 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:32:09 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:32:09.176970 2023] [ssl:info] [pid 30] [client 127.0.0.1:58824] AH01964: Connection to child 2 established (server www.example.com:443)
[Sat Jun 24 12:32:09.179451 2023] [ssl:info] [pid 30] [client 127.0.0.1:58824] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:32:09.179469 2023] [ssl:info] [pid 30] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:32:09.179474 2023] [ssl:info] [pid 30] [client 127.0.0.1:58824] AH01998: Connection closed to child 2 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:32:39 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:32:39 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:32:39.393888 2023] [ssl:info] [pid 32] [client 127.0.0.1:58942] AH01964: Connection to child 4 established (server www.example.com:443)
[Sat Jun 24 12:32:39.395927 2023] [ssl:info] [pid 32] [client 127.0.0.1:58942] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:32:39.395942 2023] [ssl:info] [pid 32] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:32:39.395947 2023] [ssl:info] [pid 32] [client 127.0.0.1:58942] AH01998: Connection closed to child 4 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:33:09 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:33:09 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:33:09.641198 2023] [ssl:info] [pid 28] [client 127.0.0.1:59126] AH01964: Connection to child 0 established (server www.example.com:443)
[Sat Jun 24 12:33:09.643758 2023] [ssl:info] [pid 28] [client 127.0.0.1:59126] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:33:09.643780 2023] [ssl:info] [pid 28] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:33:09.643787 2023] [ssl:info] [pid 28] [client 127.0.0.1:59126] AH01998: Connection closed to child 0 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:33:39 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:33:39 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:33:39.844660 2023] [ssl:info] [pid 30] [client 127.0.0.1:59216] AH01964: Connection to child 2 established (server www.example.com:443)
[Sat Jun 24 12:33:39.846321 2023] [ssl:info] [pid 30] [client 127.0.0.1:59216] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:33:39.846337 2023] [ssl:info] [pid 30] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:33:39.846343 2023] [ssl:info] [pid 30] [client 127.0.0.1:59216] AH01998: Connection closed to child 2 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:34:09 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:34:09 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:34:10.032796 2023] [ssl:info] [pid 32] [client 127.0.0.1:59360] AH01964: Connection to child 4 established (server www.example.com:443)
[Sat Jun 24 12:34:10.034785 2023] [ssl:info] [pid 32] [client 127.0.0.1:59360] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:34:10.034800 2023] [ssl:info] [pid 32] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:34:10.034806 2023] [ssl:info] [pid 32] [client 127.0.0.1:59360] AH01998: Connection closed to child 4 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:34:40 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:34:40 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:34:40.216517 2023] [ssl:info] [pid 28] [client 127.0.0.1:59456] AH01964: Connection to child 0 established (server www.example.com:443)
[Sat Jun 24 12:34:40.218178 2023] [ssl:info] [pid 28] [client 127.0.0.1:59456] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:34:40.218194 2023] [ssl:info] [pid 28] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:34:40.218199 2023] [ssl:info] [pid 28] [client 127.0.0.1:59456] AH01998: Connection closed to child 0 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:35:10 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:35:10 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:35:10.404734 2023] [ssl:info] [pid 30] [client 127.0.0.1:59604] AH01964: Connection to child 2 established (server www.example.com:443)
[Sat Jun 24 12:35:10.406714 2023] [ssl:info] [pid 30] [client 127.0.0.1:59604] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:35:10.406733 2023] [ssl:info] [pid 30] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:35:10.406739 2023] [ssl:info] [pid 30] [client 127.0.0.1:59604] AH01998: Connection closed to child 2 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:35:40 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:35:40 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:35:40.611008 2023] [ssl:info] [pid 32] [client 127.0.0.1:59694] AH01964: Connection to child 4 established (server www.example.com:443)
[Sat Jun 24 12:35:40.612994 2023] [ssl:info] [pid 32] [client 127.0.0.1:59694] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:35:40.613008 2023] [ssl:info] [pid 32] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:35:40.613014 2023] [ssl:info] [pid 32] [client 127.0.0.1:59694] AH01998: Connection closed to child 4 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:36:10 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:36:10 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:36:10.805425 2023] [ssl:info] [pid 28] [client 127.0.0.1:59882] AH01964: Connection to child 0 established (server www.example.com:443)
[Sat Jun 24 12:36:10.807445 2023] [ssl:info] [pid 28] [client 127.0.0.1:59882] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:36:10.807460 2023] [ssl:info] [pid 28] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:36:10.807465 2023] [ssl:info] [pid 28] [client 127.0.0.1:59882] AH01998: Connection closed to child 0 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:36:40 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:36:40 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:36:41.001120 2023] [ssl:info] [pid 30] [client 127.0.0.1:60004] AH01964: Connection to child 2 established (server www.example.com:443)
[Sat Jun 24 12:36:41.003350 2023] [ssl:info] [pid 30] [client 127.0.0.1:60004] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:36:41.003368 2023] [ssl:info] [pid 30] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:36:41.003386 2023] [ssl:info] [pid 30] [client 127.0.0.1:60004] AH01998: Connection closed to child 2 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:37:11 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:37:11 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:37:11.194233 2023] [ssl:info] [pid 32] [client 127.0.0.1:60188] AH01964: Connection to child 4 established (server www.example.com:443)
[Sat Jun 24 12:37:11.196210 2023] [ssl:info] [pid 32] [client 127.0.0.1:60188] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:37:11.196228 2023] [ssl:info] [pid 32] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:37:11.196234 2023] [ssl:info] [pid 32] [client 127.0.0.1:60188] AH01998: Connection closed to child 4 with abortive shutdown (server www.example.com:443)
127.0.0.1 - - [24/Jun/2023:12:37:41 +0000] "GET / HTTP/1.1" 302 45
127.0.0.1 - - [24/Jun/2023:12:37:41 +0000] "GET / HTTP/1.1" 302 45 "-" "Wget"
[Sat Jun 24 12:37:41.388922 2023] [ssl:info] [pid 28] [client 127.0.0.1:60412] AH01964: Connection to child 0 established (server www.example.com:443)
[Sat Jun 24 12:37:41.391048 2023] [ssl:info] [pid 28] [client 127.0.0.1:60412] AH02008: SSL library error 1 in handshake (server www.example.com:443)
[Sat Jun 24 12:37:41.391071 2023] [ssl:info] [pid 28] SSL Library Error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca (SSL alert number 48)
[Sat Jun 24 12:37:41.391078 2023] [ssl:info] [pid 28] [client 127.0.0.1:60412] AH01998: Connection closed to child 0 with abortive shutdown (server www.example.com:443)

**Comment by JulianPrieber** [comment] 2023-06-24 12:40
Does it run tho?

**Comment by norton287** [comment] 2023-06-24 12:46
Yes it starts and runs but it shows as unhealthy and get a 500 error when trying to connect @JulianPrieber

**Comment by JulianPrieber** [comment] 2023-06-24 12:52
Cant reproduce with the latest release.

Please try again with the test tag: `docker pull linkstackorg/linkstack:test`

**Comment by norton287** [comment] 2023-06-24 12:58
Test works perfect @JulianPrieber

**Comment by JulianPrieber** [comment] 2023-06-24 12:59
Test and latest should be identical. I'll mark this as solved for now.

**Closed by JulianPrieber** 2023-06-24 12:59 UTC
